/**
 * 
 * Goes over all available files in the specified INPUT_FOLDER 
 * and parses them for data, adding them to the SPREADSHEET_DATA_EXTRACTION,
 * 
 * After being parsed the files will be moved to the PROCESSED_FOLDER.
 * 
 */


/**
 * Add sheet names, and their pdf type, headers, and special notes IN ORDER here!
 * 
 * Used for reports we already know everything for...
 */
const SHEET_NAMES = ["Campaign Data"];
const PDF_TYPES = ["campaign"];
const PDF_HEADERS = [["Name", "Additional Info / Stations", "Reach", "Rating", "Favorite Track", "Comments"]];
const PDF_PARSING_NOTES = ["Note: For the 'Not For Me' section, capture the Name and Additional Info only. Put in 'Not for me' in the comments section as well. "];
const PARSER_INPUT_FOLDER =
  PropertiesService.getScriptProperties()
    .getProperty("PARSER_INPUT_FOLDER");

const PARSER_OUTPUT_FOLDER =
  PropertiesService.getScriptProperties()
    .getProperty("PARSER_OUTPUT_FOLDER");

function processNewPDFs() {
  const folder = DriveApp.getFolderById(PARSER_INPUT_FOLDER);
  const targetFolder = DriveApp.getFolderById(PARSER_OUTPUT_FOLDER); 

  // 1. Convert Word docs to PDF
  checkForDocxFiles(folder, targetFolder);

  // 2. Handle CSV files directly
  processCsvFiles(folder, targetFolder);

  /**
   * Parse all PDF input files!
   */
  const files = folder.getFilesByType(MimeType.PDF);
  if (!files.hasNext()) return;
  
  while(files.hasNext()){
    var file = files.next();
    const blob = file.getBlob();
    parseUndefinedFile(file, blob, targetFolder);
  }
}

/**
 * Finds CSV files, parses them, adds them to the spreadsheet, and moves them to the target folder.
 */
function processCsvFiles(folder, targetFolder) {
  const csvFiles = folder.getFilesByType(MimeType.CSV);
  const ss = SpreadsheetApp.openByUrl("https://docs.google.com/spreadsheets/d/" + SPREADSHEET_DATA_EXTRACTION + "/edit");

  while (csvFiles.hasNext()) {
    const file = csvFiles.next();
    const fileName = file.getName().replace(/\.csv$/i, "");
    
    // Parse the CSV content
    const csvData = Utilities.parseCsv(file.getBlob().getDataAsString());
    
    if (csvData.length > 0) {
      let sheet = ss.getSheetByName(fileName);
      
      // If sheet exists, maybe clear it or just create a new one with a unique name
      if (sheet) {
        // Option A: Clear existing (Uncomment if preferred)
        // sheet.clear(); 
        
        // Option B: Create unique name (Standard approach)
        sheet = ss.insertSheet(fileName + "_" + new Date().getTime());
      } else {
        sheet = ss.insertSheet(fileName);
      }

      // Write the CSV data to the sheet
      sheet.getRange(1, 1, csvData.length, csvData[0].length).setValues(csvData);
      sheet.getDataRange().setWrapStrategy(SpreadsheetApp.WrapStrategy.WRAP);
    }

    // Move to target folder
    file.moveTo(targetFolder);
    console.log("Processed CSV: " + fileName);
  }
}

/**
 * Parses the file using headers generated by gemini itself.
 */
function parseUndefinedFile(file, blob, targetFolder){
  const ss = SpreadsheetApp.openByUrl("https://docs.google.com/spreadsheets/d/" + SPREADSHEET_DATA_EXTRACTION + "/edit");
    ss.getDataRange().setWrapStrategy(SpreadsheetApp.WrapStrategy.WRAP);

    //Make the indiv sheet if needed...
    let fileName = file.getName();
    // The $ ensures it only removes .pdf if it's at the very end
    fileName = fileName.replace(/\.pdf$/i, ""); 
    var sheet = null;
    if(ss.getSheetByName(fileName) == null){
      sheet = ss.insertSheet(fileName);
    }else{
      sheet = ss.getSheetByName(fileName);
    }

    const response = geminiParsePDFUndefined(blob);

    const result = JSON.parse(response.getContentText());
    console.log("GEMINI OUTPUT FOR FILE: " + fileName + "\n" + JSON.stringify(result));

    // Safety check: if Gemini is blocked or errors out
    if (!result.candidates || !result.candidates[0].content) {
      console.error("Gemini returned no data: " + response.getContentText());
      return;
    }

    const textResponse = result.candidates[0].content.parts[0].text;
    const cleanJson = textResponse.replace(/```json|```/g, "").trim();
    const data = JSON.parse(cleanJson);

    const headers = Object.keys(data[0]);
    if (sheet.getLastRow() === 0) {
      sheet.appendRow(headers);
    }
    const rows = data.map(obj => headers.map(h => obj[h] ?? ""));
    sheet.getRange(sheet.getLastRow() + 1, 1, rows.length, headers.length)
     .setValues(rows);
    
    file.moveTo(targetFolder);  //Send to used files folder.
}

function geminiParsePDFUndefined(blob){
  /**
   * FIX: We explicitly tell Gemini to use your header strings as JSON keys.
   */
  const prompt = "Extract all feedback data from this PDF into a JSON array. " +
                 "Headers should be defined as needed for the data from the PDF first." +
                 " Return ONLY the raw JSON array." + 
                 "Additionally, for names, make the first and last name separate as well as " +
                 "include the email, phone number, country, city, state/Region, and Music genre " +
                  "as columns as well if mentioned in the document. If some header has no data in the document, just leave it out.";

  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${GEMINI_API_KEY}`;
  
  const payload = {
    contents: [{
      parts: [
        { text: prompt },
        { inline_data: { mime_type: "application/pdf", data: Utilities.base64Encode(blob.getBytes()) }}
      ]
    }]
  };

  return UrlFetchApp.fetch(url, {
    method: "post",
    contentType: "application/json",
    payload: JSON.stringify(payload),
    muteHttpExceptions: true
  });
}

/**
 * SWITCH CASES FOR PDF_TYPE SHEET HEADERS!
 * Adds the header for the sheet if not present...
 * 
 * sheetToUse - tells the type of PDF!
 */
function setSheetHeaders(sheetToUse, sheet){
  switch(PDF_TYPES[sheetToUse]){
    case PDF_TYPES[0]:  
      if(sheet.getLastRow() === 0){
        sheet.appendRow(PDF_HEADERS[0]);
      }
      break;
    default: 
      break;
  }
}

/**
 * Checks for docx files in the folder (input files folder)
 * Then converts them to pdfs, with the old docx reports moving to targetFolder.
 */
function checkForDocxFiles(folder, targetFolder){
  /**
   * Convert any potential docx files...
   */
  const filesToConvert = folder.getFilesByType(MimeType.MICROSOFT_WORD);
  while (filesToConvert.hasNext()){
    const file = filesToConvert.next();
    convertDocxToPdf(file.getId(), file.getName().replace(/\.(docx?|DOCX?)$/, ""), targetFolder);
  }
}


/**
 * Docx to pdf converter script!
 * 
 * fileId - file id to change from docx to pdf.
 * docName - name of the document without .docx
 * targetFolder - name of the folder to move the parsed docx to when turned to a pdf.
 */
function convertDocxToPdf(fileId, docName, targetFolder) {
  const file = DriveApp.getFileById(fileId);
  const parent = file.getParents().next();

  let pdfBlob;

  try {
    // Try direct DOCX → PDF export
    const url = `https://www.googleapis.com/drive/v3/files/${fileId}/export?mimeType=application/pdf&alt=media`;
    const token = ScriptApp.getOAuthToken();
    const response = trackedFetch("Google Drive API", url, {
      headers: { Authorization: `Bearer ${token}` }
    });

    pdfBlob = response.getBlob();
  } catch (e) {
    // Fallback: convert DOCX → Google Doc → PDF
    const gdoc = Drive.Files.copy(
      { mimeType: "application/vnd.google-apps.document" },
      fileId
    );

    const url = `https://www.googleapis.com/drive/v3/files/${gdoc.id}/export?mimeType=application/pdf&alt=media`;
    const token = ScriptApp.getOAuthToken();
    const response = trackedFetch("Google Drive API", url, {
      headers: { Authorization: `Bearer ${token}` }
    });

    pdfBlob = response.getBlob();

    DriveApp.getFileById(gdoc.id).setTrashed(true);
  }

  pdfBlob.setName(docName + ".pdf");

  const pdfFile = parent.createFile(pdfBlob);

  targetFolder.addFile(file);
  parent.removeFile(file);

  return pdfFile.getId();
}